import type { Metadata } from "next";
import { Provider } from "@/redux";
import { Cairo } from "next/font/google";
import { Setup } from "@/Components/utils";
import CustomLayout from "./CustomLayout";
import "./globals.css";


const cairo = Cairo({ subsets: ["latin"],display: 'swap', adjustFontFallback: false});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.className} antialiased light`}
      >
        <Provider>
          <Setup />
            <CustomLayout>
              {children}
            </CustomLayout>
        </Provider>
      </body>
    </html>
  );
}
